### ISSUE TITLE
cannot load such file -- lib/json/ld/preloaded/activitystreams.rb

### ISSUE THREAD

**Issue by njh** [ruby-rdf/json-ld-preloaded#1]
I found removing the 'lib/' from each of the `load` lines in `json/ld/preloaded.rb` fixed my problem.

**Comment by gkellogg** [comment]
Okay,my hat would be a bug; not sure why specs didn't find it.

**Comment by gkellogg** [comment]
Okay, fixed and released as 0.0.1.
