### ISSUE TITLE
ActivityStreams wrong context URI

### ISSUE THREAD

**Issue by Gargron** [ruby-rdf/json-ld-preloaded#2]
The normative context for ActivityStreams is `https://www.w3.org/ns/activitystreams`. In this gem, it has `.jsonld`at the end, which means the preload is not actually used for real ActivityStreams documents.

**Comment by gkellogg** [comment]
Thanks for the note, I'll release an update tomorrow.

**Comment by gkellogg** [comment]
Released in 2.2.1.
