### ISSUE TITLE
Linked Data Signatures context

### ISSUE THREAD

**Issue by Gargron** [ruby-rdf/json-ld-preloaded#3]
Sorry I didn't bring this up earlier, I didn't realize I needed it: `https://w3id.org/identity/v1`

Used by <https://w3c-dvcg.github.io/ld-signatures/>

Apparently I need to include that context in my hash before giving it to rdf-normalize, otherwise the output of normalize is an empty string.

**Comment by gkellogg** [comment]
Released in 2.2.2.

**Comment by Gargron** [comment]
Thank you.
